highlighter: pygments
timezone: America/New_York
title: Slim Framework
url: http://www.slimframework.com
slim_website_repo: https://github.com/slimphp/Slim-Website/tree/gh-pages/
urlBasePath:
include: [.htaccess]
exclude: [node_modules]
gems:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      docs:
        - title: Get Started
          items:
            - [/docs, Home]
            - [/docs/start/installation.md, Installation]
            - [/docs/start/upgrade.md, Upgrade Guide]
            - [/docs/start/web-servers.md, Web Servers]
        - title: Concepts
          items:
            - [/docs/concepts/value-objects.md, PSR 7]
            - [/docs/concepts/middleware.md, Middleware]
            - [/docs/concepts/di.md, Dependency Container]
        - title: Objects
          items:
            - [/docs/objects/request.md, Request]
            - [/docs/objects/response.md, Response]
            - [/docs/objects/router.md, Router]
            - [/docs/objects/environment.md, Environment]
        - title: Features
          items:
            - [/docs/features/templates.md, Templates]
            - [/docs/features/caching.md, HTTP Caching]
            - [/docs/features/csrf.md, CSRF Protection]
            - [/docs/features/flash.md, Flash Messages]
        - title: Error Handling
          items:
            - [/docs/handlers/error.md, 500 Server Error]
            - [/docs/handlers/not-found.md, 404 Not Found]
            - [/docs/handlers/not-allowed.md, 405 Not Allowed]
        - title: Contributing
          items:
            - [/docs/contributors/strategy.md, Branching Strategy]
            - [/docs/contributors/guidelines.html, Guidelines]
  -
    scope:
      path: "docs"
      type: "pages"
    values:
      layout: docs
